design-patterns:
  name: design-patterns 
  description: Lv 0 부터 시작하는 디자인 패턴
  cover: assets/built/images/background-frontend.png

spring:
  name: spring 
  description: Lv 0 부터 시작하는 스프링 프레임워크
  cover: assets/built/images/background-frontend.png

book:
  name: book
  description: Lv 0 부터 시작하는 독서연대기
  cover: assets/built/images/background-frontend.png